[Icon Theme]
Name=TaskCoach
Comment=TaskCoach application icons
Directories=16x16,22x22,32x32,48x48,64x64,128x128

[16x16]
Size=16
Context=Actions
Type=Threshold

[22x22]
Size=22
Context=Actions
Type=Threshold

[32x32]
Size=32
Context=Actions
Type=Threshold

[48x48]
Size=48
Context=Actions
Type=Threshold

[64x64]
Size=64
Context=Actions
Type=Threshold

[128x128]
Size=128
Context=Actions
Type=Threshold
